# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
name: Build and deploy Node.js app to Azure Web App - WeGo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Preferably using the LTS version

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps # Install dependencies, ignoring peer dependency conflicts

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "node_modules/*" ".git/*" ".github/*" # Create zip excluding unnecessary directories

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure this secret is added

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip # Unzip the application files for deployment

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WeGo'  # Replace with your Azure App Service name
          slot-name: 'Production'
          package: .  # Path to the location where the application files are unzipped
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }} # Ensure you have this secret set